### ISSUE TITLE
This extension is not mentioned in the official docs.

### ISSUE THREAD

**Issue by g-berthiaume** [asabil/vscode-meson#90]
Is this the official vscode meson extension?
If so, it's not listed in the official documentation.
https://mesonbuild.com/IDE-integration.html#existing-integrations

**Comment by Ongy** [comment]
Maybe with a PR, not a report ;)

And yes, that's on the documentation side. I have larger pains with this exension not being the top one in the store. But there's not much we can do against that outside gaining more users.
